spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/swish
    username: guuri11
    driver-class-name: or.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect